name: Magic Flowers
favicon: null
layout_spectrum: 0.88318
typography_spectrum: 0.36076
title: Magic Moments Floral Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#89c15b'
    - '#cfe6ae'
    - '#b0cb85'
    - '#b7d993'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
