name: Magic Flowers
favicon: null
layout_spectrum: 0.09903437364846468
typography_spectrum: 0.8422931898385286
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.10427795443683863
  lightness: 0.4382377516012639
  saturation: 0.8501190855167806
  rhythmicContrast: 0.2354741336312145
purpose: []
