name: Magic Flowers
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.8422931898385286
title: Magic Moments Floral Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#635b54'
    - '#ffffff'
    - '#d1ccb8'
    - '#a7937e'
    - '#69245d'
  brandStrength: 0.10427795443683863
  lightness: 0.5625
  saturation: 0.8501190855167806
  rhythmicContrast: 0
purpose: []
